### PR TITLE
new post: updates and roadmap

### PR DESCRIPTION
**Pull request by eparejatobes**

### CODE REVIEW

**Comment by eparejatobes** [comment]
Hey @pablopareja @marina-manrique @rtobes @epareja could you take a look at this? I'm writing a new post for the blog.

**Comment by eparejatobes** [comment]
I decided it would read better if we limit this first post to a basic general description of the changes we have now

**Comment by eparejatobes** [comment]
We can talk about the future in the next post

**Comment by eparejatobes** [comment]
@pablopareja @rtobes please review

**Comment by eparejatobes** [comment]
got +1 through other sources, merging

**Comment by rtobes** [comment]
Go ahead with the post!

**Comment by pablopareja** [comment]
cool! I'm gonna tweet it, post a message in the linkedIn group and so on... :wink:

**Comment by eparejatobes** [comment]
great, I didn't do any of that

**Pull request merged**
